<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<%@ include file="/common/tld-common.jsp"%>

<%
	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"+ request.getServerName() + ":" + request.getServerPort()+ path + "/";
%>
<base href="<%=basePath%>">
<html>
<head>
	<title>Follow Up History > Edit</title>
	<%@ include file="/common/sirius-header.jsp"%>
	<%@ include file="/common/popup.jsp"%>
	<style type="text/css" media="screen">
		@import url("<c:url value='/assets/sirius.css'/>");
		@import url("<c:url value='/css/jquery-ui.css'/>");
	</style>
</head>
<!-- BEGIN OF BODY -->
<body>

<!-- top  menu -->
	
<!-- /top menu -->

<!-- rounded -->
<div id="se-r00">
	<div id="se-r01">&nbsp;</div>
	<div id="se-r02">&nbsp;</div>
</div>

<div id="se-containers">

		<%@ include file="/common/sirius-menu.jsp"%>

	<div id="se-navigator">
		<table border="0" cellpadding="0" cellspacing="0" width="100%">
		<tr>
			<td width="60%">Sales > Follow Up History > Edit</td>
			<td width="40%" align="right"><%@ include file="/common/welcome.jsp"%></td>
		</tr>
		</table>
	</div>

	<div id="r11">
		<div id="r12">
			<div id="r13">
				<div id="r14">
					<div id="se-contents">
						
					<h1 class="page-title">S08 - Follow Up History</h1>
						
					<div class="toolbar">
						<a class="item-button-list" href="<c:url value='/page/followuphistoryview.htm'/>"><span>List</span></a>
						<a class="item-button-save b_save" style="cursor:pointer"><span>Save</span></a>
					</div>					  
					  
					<div class="main-box">
						<form:form id="addForm" name="addForm" method="post" modelAttribute="followUp_edit">
							<table width="100%" border="0">
	 						<tr>&nbsp;</tr>
							<tr>
								<td width="27%" nowrap="nowrap" align="right">ID :</td>
								<td width="73%"><input value="AUTOGENERATED" disabled='true' class='input-disabled' size='30'/></td>
							</tr>
	 						<tr>
								<td align="right">Customer Name :</td>
								<td>
	                             	<form:select id="customer" path="customer" cssClass="combobox-ext input-disabled" disabled='true'>
	                             		<form:option value='${followUp_edit.customer.id}' label='${followUp_edit.customer.firstName} ${followUp_edit.customer.middleName} ${followUp_edit.customer.lastName}' />
	                                </form:select>
	                            </td>
							</tr>
							<tr>
								<td align="right">Follow Up Date :</td>
								<td colspan="2"><input value="<fmt:formatDate value='${followUp_edit.prevDate}' pattern='dd-MM-yyyy'/>" disabled='true' class='input-disabled' size='15'/></td>
							</tr>
	 						<tr>
								<td align="right">Motor :</td>
								<td>
	                             	<form:select id="product" path="product" cssClass="combobox-ext input-disabled" disabled='true'>
	                             		<form:option value='${followUp_edit.product.id}' label='${followUp_edit.product.name}' />
	                                </form:select>
	                            </td>
							</tr>
	 						<tr>
								<td align="right">Sales Person :</td>
								<td>
	                             	<form:select id="salesperson" path="salesPerson" cssClass="combobox-ext input-disabled" disabled='true'>
	                             		<form:option value='${followUp_edit.salesPerson.id}' label='${followUp_edit.salesPerson.firstName} ${followUp_edit.salesPerson.middleName} ${followUp_edit.salesPerson.lastName}' />
	                                </form:select>
	                            </td>
							</tr>			
							<tr>
								<td align="right">Follow Up Type :</td>
								<td>
		    						<div class="form-value">
	 									<form:select path="type" disabled='true' cssClass="combobox input-disabled">
	 										<c:if test='${not empty followUp_edit.type}'>
	                                            <form:option value='${followUp_edit.type.id}' label='${followUp_edit.type.name}' />
	                                        </c:if>
										</form:select>
									</div>
								</td>
							</tr>
							<tr>
								<td align="right">Note :</td>
								<td><form:textarea path='note' cols='55' rows='6'/></td>
							</tr>
							<tr>
								<td align="right">Next Follow Up Date :</td>
								<td colspan="2"><input value="<fmt:formatDate value='${followUp_edit.nextDate}' pattern='dd-MM-yyyy'/>" disabled='true' class='input-disabled' size='15'/></td>
							</tr>
	                        <tr>
								<td align="right">Agenda :</td>
								<td><form:textarea path='agenda' cols='55' rows='6'/></td>
							</tr>
	 						</table>
						</form:form>
					</div>
					<div class="info">Created by : <c:out value='${followUp_edit.createdBy.firstName} ${followUp_edit.createdBy.middleName} ${followUp_edit.createdBy.lastName}'/> (<fmt:formatDate value='${followUp_edit.createdDate}' pattern='dd-MM-yyyy HH:mm:ss'/>) | Last update by : <c:out value='${followUp_edit.updatedBy.firstName} ${followUp_edit.updatedBy.middleName} ${followUp_edit.updatedBy.lastName}'/> (<fmt:formatDate value='${followUp_edit.updatedDate}' pattern='dd-MM-yyyy HH:mm:ss'/>)</div>
				</div>
				</div>
			</div>
		</div>
	</div>
  	
  	<div style="clear:both;height:0px">&nbsp;</div>
	<div id="footer">
		<div>
			<span>&copy; 2007 siriusERP v1.0GA&nbsp;&nbsp;&nbsp;&nbsp;</span>
		</div>
	</div>
	<div style="clear:both;height:20px">&nbsp;</div>

	<!-- /footer -->
</div><!-- /main containers -->
</body>
<!-- END OF BODY -->
</html>
<script type="text/javascript">
$(function()
{
	var $dialog = $('<div></div>').dialog({autoOpen: false,title: 'Follow Up History',modal:true,buttons: {Close: function() {$(this).dialog('close');}}});
	$('.b_save').click(function(e)
	{
		if($("#customer").val() == '')
		{
			alert('Please select Customer first !!!');
			return;
		}
		
		if($("#prevdateid").val() == '')
		{
			alert('Follow Up Date cannot be empty !!!');
			return;
		}
		
		if($("#product").val() == '')
		{
			alert('Please select Product first !!!');
			return;
		}
		
		if($("#salesperson").val() == '')
		{
			alert('Please select Sales Person first !!!');
			return;
		}
		
		if($("#nextdateid").val() == '')
		{
			alert('Next Follow Up Date cannot be empty !!!');
			return;
		}
		
		$.ajax({
			url:"<c:url value='/page/followuphistoryedit.htm'/>",
			data:$('#addForm').serialize(),
			type : 'POST',
			dataType : 'json',
			beforeSend:function()
			{
				$dialog.empty();
				$dialog.html('Updating Follow Up History data......');
				$dialog.dialog('open');
			},
			success : function(json)
			{
				if(json)
				{
					if(json.status == 'OK')
					{
						$dialog.dialog('close');
						window.location="<c:url value='/page/followuphistoryview.htm?'/>";
					}
					else
					{
						$dialog.empty();
						$dialog.html('Proccess fail,reason:<br/>'+json.message);
					}
				}
			}
		});
	});
});
</script>
